create database Customer_Behavior;
use Customer_Behavior;
show tables;
select * from customer;
DESCRIBE customer;
ALTER TABLE customer
RENAME COLUMN `ï»¿Customer ID` TO `Customer ID`;
SHOW COLUMNS FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender,
       SUM(`Purchase Amount (USD)`) AS Revenue FROM customer GROUP BY Gender;
       
	-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
    SELECT `Customer ID`, `Purchase Amount (USD)` FROM customer
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` >= (
      SELECT AVG(`Purchase Amount (USD)`) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS Average_Product_Rating
FROM customer GROUP BY `Item Purchased` ORDER BY AVG(`Review Rating`) DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS Avg_Purchase_Amount
FROM customer
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT `Subscription Status`,
       COUNT(*) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) AS discount_rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT `Customer ID`,
           `Previous Purchases`,
           CASE
               WHEN `Previous Purchases` = 1 THEN 'New'
               WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment, COUNT(*) AS Number_of_Customers FROM customer_type GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT `Category`,
           `Item Purchased`,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY `Category`
               ORDER BY COUNT(*) DESC
           ) AS item_rank
    FROM customer
    GROUP BY `Category`, `Item Purchased`
)

SELECT item_rank, `Category`, `Item Purchased`, total_orders
FROM item_counts WHERE item_rank <= 3 ORDER BY `Category`, item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status`,
       COUNT(*) AS repeat_buyers
FROM customer
WHERE `Previous Purchases` > 5
GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age group? 
SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Young Adults'
        WHEN Age BETWEEN 26 AND 35 THEN 'Adults'
        WHEN Age BETWEEN 36 AND 45 THEN 'Middle Aged'
        WHEN Age BETWEEN 46 AND 56 THEN 'Senior'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customer
WHERE Age BETWEEN 18 AND 55
GROUP BY age_group
ORDER BY total_revenue DESC;